// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc20.LaunchPad.subsystems;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc20.LaunchPad.commands.CatcherPanelOutCommand;

/**
 *
 */
public class CatcherPanel extends Subsystem {

    private DoubleSolenoid doubleSolenoid;

    public CatcherPanel(int moduleNumber, int forwardChannel, int reverseChannel) {
        doubleSolenoid = new DoubleSolenoid(moduleNumber, forwardChannel, reverseChannel);
    }
    
    protected void initDefaultCommand() {
        setDefaultCommand(new CatcherPanelOutCommand(this));
    }

    public void out() {
        doubleSolenoid.set(DoubleSolenoid.Value.kForward);
    }

    public void in() {
        doubleSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
    

    public boolean isOut() {
        return doubleSolenoid.get().equals(DoubleSolenoid.Value.kForward);
    }
    
}
