// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc20.LaunchPad.subsystems;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Collector extends Subsystem {

    private DoubleSolenoid leftDoubleSolenoid;
    private DoubleSolenoid rightDoubleSolenoid;
    private Talon motor;

    public Collector(int leftDoubleSolenoidModuleNumber,
            int leftDoubleSolenoidForwardChannel,
            int leftDoubleSolenoidReverseChannel,
            int rightDoubleSolenoidModuleNumber,
            int rightDoubleSolenoidForwardChannel,
            int rightDoubleSolenoidReverseChannel,
            int rollerMotorChannel) {
        leftDoubleSolenoid = new DoubleSolenoid(leftDoubleSolenoidModuleNumber,
                leftDoubleSolenoidForwardChannel,
                leftDoubleSolenoidReverseChannel);

        rightDoubleSolenoid = new DoubleSolenoid(rightDoubleSolenoidModuleNumber,
                rightDoubleSolenoidForwardChannel,
                rightDoubleSolenoidReverseChannel);

        motor = new Talon(rollerMotorChannel);

    }

    public void initDefaultCommand() {

    }

    public void extendCollector() {
        leftDoubleSolenoid.set(DoubleSolenoid.Value.kForward);
        rightDoubleSolenoid.set(DoubleSolenoid.Value.kForward);

    }

    public void retractCollector() {
        leftDoubleSolenoid.set(DoubleSolenoid.Value.kReverse);
        rightDoubleSolenoid.set(DoubleSolenoid.Value.kReverse);
    }

    public void driveCollector(double speed) {
        motor.set(speed);
    }

    public void stopCollector() {
        motor.set(0);
    }

    public boolean isDrivingForward() {
        return motor.get() > 0;
    }

    public boolean isStopped() {
        return motor.get() == 0;
    }

    public boolean isDrivingBackwards() {
        return motor.get() < 0;
    }

    public boolean isExtended() {
        return leftDoubleSolenoid.get().equals(DoubleSolenoid.Value.kForward)
                && rightDoubleSolenoid.get().equals(DoubleSolenoid.Value.kForward);
    }
}
