// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc20.LaunchPad.subsystems;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc20.LaunchPad.commands.DrivetrainGearboxShiftHighCommand;

/**
 *
 */
public class DrivetrainGearbox extends Subsystem {

    private final DoubleSolenoid shifter;
    
    public DrivetrainGearbox(int moduleNumber, int shifterForwardChannel, int shifterReverseChannel){
        shifter = new DoubleSolenoid(moduleNumber, shifterForwardChannel, shifterReverseChannel);
    }
    
    public void shiftToHigh(){
        shifter.set(DoubleSolenoid.Value.kForward);
    }
    
    public void shiftToLow(){
        shifter.set(DoubleSolenoid.Value.kReverse);
    }
    
    protected void initDefaultCommand() {
        setDefaultCommand(new DrivetrainGearboxShiftHighCommand());
    }
    
}