// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc20.LaunchPad.subsystems;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Gyro;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 * @author Jared Gentner
 * @author Jacob Melite
 */
public class Drivetrain extends Subsystem {

    /**
     * Used in the PID controllers in this class. Makes it easier to control the
     * controllers and reduces necessary computations by only needing to
     * calculate once, and writing to 3 controllers at once instead of 3
     * separate controllers.
     *
     */
    private class Source implements PIDOutput {

        Talon m1;
        Talon m2;
        Talon m3;

        Source(Talon t1, Talon t2, Talon t3) {
            m1 = t1;
            m2 = t2;
            m3 = t3;
        }

        public void pidWrite(double t1) {
            m1.set(t1);
            m2.set(t1);
            m3.set(t1);
        }

    }

    Gyro gyro;
    private Talon leftTalon1, leftTalon2, leftTalon3;
    private Talon rightTalon1, rightTalon2, rightTalon3;
    // PIDController leftBrake1, leftBrake2, leftBrake3;
    //PIDController rightBrake1, rightBrake2, rightBrake3;
    PIDController leftBrake, rightBrake, turningController;
    Encoder leftEncoder;
    Encoder rightEncoder;

    final double P = 0, I = 0, D = 0;

    public Drivetrain(int right1, int right2, int right3,
            int left1, int left2, int left3,
            int gyroChannel, int leftEncoderChannelA, int leftEncoderChannelB,
            int rightEncoderChannelA, int rightEncoderChannelB) {

        //motor controllers
        leftTalon1 = new Talon(left1);
        leftTalon2 = new Talon(left2);
        leftTalon3 = new Talon(left3);

        rightTalon1 = new Talon(right1);
        rightTalon2 = new Talon(right2);
        rightTalon3 = new Talon(right3);

        //gyro
        gyro = new Gyro(gyroChannel);
        gyro.setPIDSourceParameter(PIDSource.PIDSourceParameter.kAngle);

        //encoders TODO: Find distanceperpulse
        leftEncoder = new Encoder(leftEncoderChannelA, leftEncoderChannelB);
        rightEncoder = new Encoder(rightEncoderChannelA, rightEncoderChannelB);
        //leftEncoder.setDistancePerPulse( );
        //rightEncoder.setDistancePerPulse( );
        leftEncoder.setPIDSourceParameter(PIDSource.PIDSourceParameter.kDistance);
        rightEncoder.setPIDSourceParameter(PIDSource.PIDSourceParameter.kDistance);

        //PID Controllers
        Source leftSource = new Source(leftTalon1, leftTalon2, leftTalon3);
        Source rightSource = new Source(rightTalon1, rightTalon2, rightTalon3);
        leftBrake = new PIDController(P, I, D, leftEncoder, leftSource);
        rightBrake = new PIDController(P, I, D, rightEncoder, rightSource);
        turningController = new PIDController(P, I, D, gyro, leftSource);
    }

    /**
     * Drives the right and left motors in arcade drive
     *
     * @param magnitude speed
     * @param diff turning
     */
    public void driveArcade(double magnitude, double diff) {
        setLeftSpeed(-magnitude + diff);//idk why this is negative - Jacob Melite
        setRightSpeed(magnitude + diff);
    }

    /**
     * sets the speed of the right talons
     *
     * @param speed a double between -1 and 1
     */
    public void setRightSpeed(double speed) {
        rightTalon1.set(speed);
        rightTalon2.set(speed);
        rightTalon3.set(speed);
    }

    /**
     * sets the speed of the left talons
     *
     * @param speed a double between -1 and 1
     */
    public void setLeftSpeed(double speed) {
        leftTalon1.set(speed);
        leftTalon2.set(speed);
        leftTalon3.set(speed);
    }

    /**
     *
     * @return the speed of leftTalon1
     */
    public double getLeftSpeed() {
        return leftTalon1.get();
    }

    /**
     *
     * @return the speed of rightTalon1
     */
    public double getRightSpeed() {
        return rightTalon1.get();
    }

    /**
     *
     * @return the current angle of the gyro
     */
    public double getHeading() {
        return gyro.getAngle();
    }

    /**
     *
     * @return the angle of the gyro % 360
     */
    public double getAdjustedHeading() {
        return gyro.getAngle() % 360;
    }

    /**
     *
     * @return the distance of the left encoder
     */
    public double getCurrentLeftEncoderDistance() {
        return leftEncoder.getDistance();
    }

    /**
     *
     * @return the distance of the right encoder
     */
    public double getCurrentRightEncoderDistance() {
        return rightEncoder.getDistance();
    }

    /**
     *
     * @return the current setpoint of <code>leftBrake</code>
     */
    public double getLeftSetpoint() {
        return leftBrake.getSetpoint();
    }

    /**
     *
     * @return the current setpoint of <code>rightBrake</code>
     */
    public double getRightSetpoint() {
        return rightBrake.getSetpoint();
    }

    /**
     *
     * @return the current setpoint of <code>turningController</code>
     */
    public double getAngleSetpoint() {
        return turningController.getSetpoint();
    }

    /**
     * disables the turningController, sets the setpoint of left and right brake
     * to their encoder's current distance, enables left and right brake
     * controllers
     */
    public void enableBrake() {
        turningController.disable();
        leftBrake.setSetpoint(leftEncoder.getDistance());
        rightBrake.setSetpoint(rightEncoder.getDistance());
        leftBrake.enable();
        rightBrake.enable();
    }

    /**
     * disables the left and right brake controllers
     */
    public void disableBrake() {
        leftBrake.disable();
        rightBrake.disable();
    }

    /**
     * disables turning controller, sets the setpoint of left and right brake to
     * <code>distance</code> + the current encoder distance, enables left and
     * right brake controllers
     *
     * @param distance
     */
    public void driveDistance(double distance) {
        turningController.disable();
        leftBrake.setSetpoint(leftEncoder.getDistance() + distance);
        rightBrake.setSetpoint(rightEncoder.getDistance() + distance);
        leftBrake.enable();
        rightBrake.enable();
    }

    /**
     * disables left and right brake controllers, sets the setpoint of turning
     * controllers to the current heading + <code>angle</code>
     *
     * @param angle
     */
    public void driveAngle(double angle) {
        leftBrake.disable();
        rightBrake.disable();
        turningController.setSetpoint(getHeading() + angle);
        turningController.enable();
    }

    /**
     * disables the turning controller
     */
    public void disableTurningController() {
        turningController.disable();
    }

    public void initDefaultCommand() {
        
    }
}
