// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc20.LaunchPad;
    

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    
    public static int catapultMotor1Channel = 1;
    public static int catapultMotor2Channel = 2;
    
    public static int catapultLimitSwitchChannel = 1;
    
    public static int catapultPneumaticModule = 2;
    public static int catapultMotorPneumaticForwardChannel = 1;
    public static int catapultMotorPneumaticReverseChannel = 2;
    public static int catapultRatchetPneumaticForwardChannel = 3;
    public static int catapultRatchetPneumaticReverseChannel = 4;
    
    public static int drivetrainGearboxPneumaticModule = 1;
    public static int drivetrainGearboxPneumaticForwardChannel = 1;
    public static int drivetrainGearboxPneumaticReverseChannel = 2;
    

    public static void init() {
    }
}
